「SinatraでシンプルなWebアプリを作る」課題の提出
wata00913/Sinatra-Memo pull request #1
Opened 2022-07-20 09:13 UTC by wata00913

確認よろしくお願いします🙇‍♂️

補足説明になります
- なるべく、MVCモデルに近づけるような構成で作成しました。
- 例外処理や排他制御は対応出来てないです。
  - 検討しましたが、自前の実装は難しいと感じたので、断念しました。
- XSS対策は、自前で簡易的なエスケープ処理をしました。
- 設定ファイルと設定内容を参照するためのクラスを作成しました。
  - 後のプラクティスで、データ保存形式をDBに変える必要があるため作成しました。
- 擬似的なインターフェースを定義したかったので、スーパークラスを作成しました(`model/memo_base_repository.rb`)。
  - 現在の実装では、スーパークラスの処理は処理が空です。スーパークラスのメソッド内でraiseを使って子クラスのメソッド定義を強制させるべきでしょうか？？

2022-07-26 06:31 UTC, func09 requested changes
XSS対策についてコメントしましたー

2022-07-26 06:31 UTC, func09 commented on README.md
> +| /memos/:id/edit | GET    | :idのメモの編集画面を表示する |
URLのリストありがとうございます。
パッと見で RESTfulなルートになっているのがわかりました 😄

2022-07-26 06:31 UTC, func09 commented on views/detail_memo.erb
> +<textarea name="content" rows="4" cols="40" disabled><%= @memo.content %></textarea><br>
```
</textarea>
<script>alert('XSS')</script>
```

こういう感じのテキストを送信すると XSSで 表示を壊して JavaScriptを実行することができました。
XSSを塞ぐように修正をお願いしますー

2022-07-26 06:31 UTC, func09 commented on test/model/memo_json_repository_test.rb
> +class MemoJSONRepositoryTest < Minitest::Test
テストを書いていただいてありがたいのですが、提出物の必須条件ではないので
軽く見るだけとさせていただきます 🙏

2022-07-26 06:31 UTC, func09 commented on app.rb
> +    ESCAPE_DICT.inject(str) { |r, (char, code)| r.gsub(char, code) }
自前で実装いいですね〜

Sinatraに同梱の `Rack::Utils.escape_html` も利用できます。
置き換える定数もほぼ同じなので、用意されているものを使う選択もありです。

2022-07-27 02:20 UTC, wata00913 commented on views/detail_memo.erb
> +<textarea name="content" rows="4" cols="40" disabled><%= @memo.content %></textarea><br>
こちらも他画面と同様に、メモの表示項目にエスケープ処理を加えました！

2022-07-27 02:23 UTC, wata00913 commented on app.rb
> +    ESCAPE_DICT.inject(str) { |r, (char, code)| r.gsub(char, code) }
`Rack::Utils.escape_html`があるのを知らなかったです！😅
こちらを使う方がコード量も少なくシンプルに書けるので、置き換えました！

2022-07-27 06:57 UTC, func09 approved these changes
コメントしましたが、提出物としては条件をクリアしているので LGTMです！

2022-07-27 06:57 UTC, func09 commented on views/edit_memo.erb
> +<textarea name="content" rows="4" cols="40"><%= escape(@memo.content) %></textarea><br>
👍

2022-07-27 06:57 UTC, func09 commented on views/detail_memo.erb
> +<textarea name="content" rows="4" cols="40" disabled><%= escape(@memo.content) %></textarea><br>
👍

2022-07-27 06:57 UTC, func09 commented on model/memo_base_repository.rb
> +class MemoBaseRepository
> 擬似的なインターフェースを定義したかったので、スーパークラスを作成しました(model/memo_base_repository.rb)。
現在の実装では、スーパークラスの処理は処理が空です。スーパークラスのメソッド内でraiseを使って子クラスのメソッド定義を強制させるべきでしょうか？？

Rubyにはインターフェースがないので、Javaなどのようにメソッドの実装を強制させることができません..。
どうしてもと言う場合、raiseを使うことになると思うのですが、Rubyらしいコードにはならないので、他のエンジニアが混乱するデメリットもありそうです。

このスーパークラスは次回のDB実装を考慮したコードだと思います。先を見越してらしてすばらしいなと思いつつ、今回の提出物で MemoJSONRepository が MemoBaseRepository を継承する理由もないですし YAGNI原則（実際に必要となるまでは追加しないのがよい）という考え方もあるので、今回は実装しなくてもよかったかな？と思いました。ご参考までに。

https://ja.wikipedia.org/wiki/YAGNI#:~:text=%22You%20ain't%20gonna%20need,%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%8E%9F%E5%89%87%E3%81%A7%E3%81%82%E3%82%8B%E3%80%82

2022-07-28 02:31 UTC, merged